// --- Projects data ---
const projects = [
  {
    name: "HRnet - WealthHealth",
    featured: true,
    desc: "Conversion d'une application RH jQuery en React avec création d'un composant tableau publié sur npm.",
    stack: ["React", "Redux", "npm", "Vite"],
    img: "../assets/img/hrnet.png",
    link: "projet-hrnet.html",
    github: "https://github.com/NGnYan/HRnet",
  },
  {
    name: "ArgentBank",
    featured: true,
    desc: "Développement front-end d'une application bancaire avec authentification et gestion d'état via Redux.",
    stack: ["React", "Redux", "REST API", "Swagger"],
    img: "../assets/img/argentbank.png",
    link: "projet-argentbank.html",
    github: "https://github.com/NGnYan/ArgentBank",
  },
  {
    name: "SportSee",
    featured: false,
    desc: "Tableau de bord d'analytics sportif avec intégration de graphiques via Recharts et appels API.",
    stack: ["React", "Recharts", "API REST", "JSDoc"],
    img: "../assets/img/sportsee.png",
    link: "projet-sportsee.html",
    github: "https://github.com/NGnYan/SportSee",
  },
  {
    name: "Kasa",
    featured: false,
    desc: "Application de location immobilière avec React Router, animations CSS et intégration de données JSON.",
    stack: ["React", "React Router", "SASS", "Vite"],
    img: "../assets/img/kasa.png",
    link: "projet-kasa.html",
    github: "https://github.com/NGnYan/Kasa",
  },
  {
    name: "Billed - SaaS RH",
    featured: true,
    desc: "Débogage et tests unitaires, d'intégration et end-to-end d'une application SaaS de notes de frais.",
    stack: ["JavaScript", "Jest", "Chrome Debugger"],
    img: "../assets/img/billed.png",
    link: "projet-billed.html",
    github: "https://github.com/NGnYan/Billed-app",
  },
  {
    name: "Les Petits Plats",
    featured: false,
    desc: "Implémentation d'un moteur de recherche performant avec comparaison d'algorithmes de filtrage.",
    stack: ["JavaScript", "HTML", "CSS", "Tailwind"],
    img: "../assets/img/lespetitsplats.png",
    link: "projet-lespetitsplats.html",
    github: "https://github.com/NGnYan/Les-Petits-Plats",
  },
  {
    name: "FishEye",
    featured: false,
    desc: "Plateforme de photographes accessible avec design patterns JavaScript, lightbox et modale de contact.",
    stack: ["JavaScript", "HTML", "CSS", "Accessibilité"],
    img: "../assets/img/fisheye.png",
    link: "projet-fisheye.html",
    github: "https://github.com/NGnYan/Front-End-Fisheye",
  },
  {
    name: "GameOn",
    featured: false,
    desc: "Formulaire interactif avec validation JavaScript pour une entreprise organisant des concours de jeux.",
    stack: ["JavaScript", "HTML", "CSS"],
    img: "../assets/img/gameon.png",
    link: "projet-gameon.html",
    github: "https://github.com/NGnYan/GameOn-website-FR",
  },
  {
    name: "OhMyFood",
    featured: false,
    desc: "Interface mobile-first d'un site de restauration avec animations CSS avancées en SASS.",
    stack: ["HTML", "SASS", "CSS", "Git"],
    img: "../assets/img/ohmyfood.png",
    link: "projet-ohmyfood.html",
    github: "https://github.com/NGnYan/OhMyFood",
  },
  {
    name: "Booki",
    featured: false,
    desc: "Intégration responsive d'une page d'accueil d'agence de voyage à partir de maquettes Figma.",
    stack: ["HTML", "CSS"],
    img: "../assets/img/booki.png",
    link: "projet-booki.html",
    github: "https://github.com/NGnYan/Booki",
  },
];
